CREATE DATABASE PRUEBA1
GO
USE PRUEBA1
GO
CREATE TABLE CARRERAS(      -- TERMINADA--
	ID VARCHAR (4) NOT NULL,
	NOMBRE VARCHAR (50) NOT NULL,
	APELLIDO VARCHAR (50) NOT NULL,
	FECHA_CREACION DATE NOT NULL CHECK (FECHA_CREACION <=GETDATE()),
	MAIL VARCHAR (50) NOT NULL UNIQUE,
	NIVEL VARCHAR(12) NOT NULL CHECK(NIVEL = 'Diplomatura' OR NIVEL = 'Pregrado' OR NIVEL='Grado' OR NIVEL='Posgrado'),
	PRIMARY KEY (ID)
	)

	CREATE TABLE CARRERAS2(      -- TERMINADA--
	ID VARCHAR (4) NOT NULL,
	NOMBRE VARCHAR (50) NOT NULL,
	APELLIDO VARCHAR (50) NOT NULL,
	FECHA_CREACION DATE NOT NULL CHECK (FECHA_CREACION <=GETDATE()),
	MAIL VARCHAR (50) NOT NULL UNIQUE,
	NIVEL VARCHAR(12) NOT NULL CHECK(NIVEL = 'Diplomatura' OR NIVEL = 'Pregrado' OR NIVEL='Grado' OR NIVEL='Posgrado'),
	PRIMARY KEY (ID)
	)