--Trabajo práctico sugerido 1A
--Normalización y creación de tablas y relaciones por código


CREATE DATABASE TPA1
GO

USE TPA1
GO
CREATE TABLE Provincias(
IDProvincia int NOT NULL PRIMARY KEY, -- int es hasta 266 / CON CLAVE PRIMARIA--
Proncia VARCHAR(50) NOT NULL,
)
GO
CREATE TABLE Localidades(
CodPostal BIGINT NOT NULL PRIMARY KEY,
IDProvincia int NOT NULL FOREIGN KEY REFERENCES Provincias(IDProvincia), 
Localidad VARCHAR (50) NOT NULL,
)
GO

CREATE TABLE Clientes(
DNI VARCHAR (10) NOT NULL,
Apellido VARCHAR (50) NOT NULL,
Nombre VARCHAR (50) NOT NULL,
Sexo char NOT NULL CHECK (Sexo ='M' OR Sexo='F'),
Telefono VARCHAR (15) NOT NULL,
Mail VARCHAR (50) NOT NULL,
Fecha_Alta DATE NOT NULL,
Fecha_Nacimiento DATE NOT NULL,
Direccion Varchar (50) not null,
CodPostal BIGINT not null FOREIGN KEY REFERENCES Localidades (CodPostal), 
)

GO

CREATE TABLE Vendedores(
Legajo INT NOT NULL PRIMARY KEY,
Apellido VARCHAR (50) NOT NULL,
Nombre VARCHAR (50) NOT NULL,
Sexo CHAR NOT NULL CHECK(Sexo='M' OR Sexo='F'),
Telefono VARCHAR(15) NOT NULL,
Fecha_Ingreso DATE NOT NULL,
Fecha_Nacimiento DATE NOT NULL,
Direccion VARCHAR(50) NOT NULL,
CodPostal BIGINT NOT NULL FOREIGN KEY REFERENCES Localidades (CodPostal),
Sueldo SMALLMONEY NOT NULL ,
)

GO

CREATE TABLE MARCAS(
IDMARCA INT NOT NULL,
MARCA VARCHAR(50) NOT NULL,
)

GO

CREATE TABLE TIPOS_ARTICULOS(
 IDTIPOARTICULO INT NOT NULL,
 TIPO_ARTICULO VARCHAR(50) NOT NULL,
)

GO 

CREATE TABLE ARTICULOS (
CODIGO VARCHAR (6) NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR (50) NOT NULL,
IDMARCA INT NOT NULL FOREIGN KEY REFERENCES MARCAS(IDMARCA),
IDTIPOARTICULO INT NOT NULL FOREIGN KEY REFERENCES TIPOS_ARTICULOS(IDTIPOARTICULO),
PRECIO_COMPRA SMALLMONEY NOT NULL,
PRECIO_VENTA SMALLMONEY NOT NULL,
STOCK INT NOT NULL,
STOCK_MINIMO INT NOT NULL,
ESTADO BIT NOT NULL,
)

GO

CREATE TABLE VENTAS(
NROVENTA BIGINT NOT NULL PRIMARY KEY,
FECHA DATE NOT NULL,
CLIENTE VARCHAR(50) NOT NULL,
VENDEDOR VARCHAR (50) NOT NULL,
FORMA_PAGO CHAR CHECK(FORMA_PAGO='E'OR FORMA_PAGO='T'),
IMPORTE SMALLMONEY NOT NULL,
)

GO

CREATE TABLE DETALLE_VENTAS(
NROVENTA BIGINT NOT NULL FOREIGN KEY REFERENCES VENTAS(NROVENTA),
ARTICULO VARCHAR(6) NOT NULL FOREIGN KEY REFERENCES ARTICULOS(CODIGO),
PRECIO SMALLMONEY NOT NULL,
CANTIDAD INT NOT NULL,
)

GO

ALTER TABLE MARCAS
ADD CONSTRAINT PK_MARCAS PRIMARY KEY (IDMARCA)

GO

ALTER TABLE TIPOS_ARTICULOS 
ADD CONSTRAINT PK_TIPOS_ARTICULOS PRIMARY KEY(IDTIPOARTICULO)

ALTER TABLE VENTAS
ADD CONSTRAINT PK_VENTAS FOREIGN KEY REFERENCES VENDEDORES(LEGAJO)

ALTER TABLE VENTAS ALTER COLUMN VENDEDOR INT

alter table VENTAS
  modify VENDEDOR INT NOT null FOREIGN KEY REFERENCES VENDEDORES(LEGAJO)