--RELACION (1:1)--
CREATE DATABASE TP1_2_RELACION_UNO_A_UNO
GO
USE TP1_2_RELACION_UNO_A_UNO
GO
CREATE TABLE ALUMNOS(
	LEGAJO INT NOT NULL IDENTITY(1000,1) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	DNI VARCHAR(8) NOT NULL UNIQUE,
	FECHA_NACIMEINTO DATE NOT NULL
)

CREATE TABLE REDES_SOCIALES(
	LEGAJO INT NOT NULL,
	NOMBRE_RED_SOCIAL VARCHAR(50),
	ID_RED_SOCIAL VARCHAR(60) UNIQUE,
	FOREIGN KEY (LEGAJO) REFERENCES ALUMNOS(LEGAJO),
)

CREATE TABLE CUIL(
	LEGAJO INT NOT NULL UNIQUE,
	CUIL VARCHAR (11) NOT NULL UNIQUE,



)