CREATE DATABASE ACTIVIDAD1
GO
USE ACTIVIDAD1
GO
CREATE TABLE CARRERAS(      -- TERMINADA--
	ID VARCHAR (4) NOT NULL,
	NOMBRE VARCHAR (50) NOT NULL,
	APELLIDO VARCHAR (50) NOT NULL,
	FECHA_CREACION DATE NOT NULL DEFAULT GETDATE(),
	MAIL VARCHAR (50) NOT NULL UNIQUE,
	NIVEL VARCHAR(12) NOT NULL CHECK(NIVEL = 'Diplomatura' OR NIVEL = 'Pregrado' OR NIVEL='Grado' OR NIVEL='Posgrado'),
	PRIMARY KEY (ID)
)
GO
CREATE TABLE ALUMNOS (
	LEGAJO BIGINT NOT NULL UNIQUE IDENTITY(1000,1),
	IDCARRERA VARCHAR(4) NOT NULL,
	APELLIDOS VARCHAR (50) NOT NULL,
	NOMBRE VARCHAR (50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL DEFAULT (GETDATE()) CHECK (FECHA_NACIMEINTO<=SELECT GETDATE()),
	MAIL VARCHAR(50) NOT NULL UNIQUE,
	TELEFONO VARCHAR(15) NULL,
	PRIMARY KEY (LEGAJO),
	FOREIGN KEY (IDCARRERA) REFERENCES CARRERAS (ID)
)
GO
CREATE TABLE MATERIAS(
	ID BIGINT NOT NULL IDENTITY (1,1),
	IDCARRERA VARCHAR(4) NOT NULL,
	NOMBRE VARCHAR (50) NOT NULL,
	CARGA_HORARIA TINYINT NOT NULL CHECK(CARGA_HORARIA >=0), --tinyint PARA NUMERO ENTEROS--
	FOREIGN KEY (IDCARRERA) REFERENCES CARRERAS(ID)
)
GO
ALTER TABLE MATERIAS
ADD CONSTRAINT PK_MSTERIAS PRIMARY KEY (ID)